version: '3.4'

services:
  githubtestespipeline:
    image: githubtestespipeline
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 4
      placement:
        spread:
          - node.id
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
